# Generated by Django 2.2.12 on 2020-04-14 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='00000'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='/media/images/index.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 11, 23, 58, 753068)),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
